// Basis-Trainingsplan (Home Gym) — Ausgangszustand für den jeweiligen Zyklus.
// Wird zur Laufzeit durch geloggte Trainings automatisch fortgeschrieben (siehe progression.js -> exerciseTargets in store.js).
// repType: "range" (Wdh.-Spanne) | "fixed" (feste Wdh./Zahl) | "perSide" (Wdh. pro Seite) | "time" (Sekunden Arbeit) | "special21" (21er-Methode)
// loadType steuert die Eingabefelder in der Trainingsansicht:
//   barbell/dumbbell/kettlebell -> Gewicht + Wdh. je Satz
//   bodyweight -> nur Wdh. (z. B. Bänder, deren Widerstand sich nicht in kg beziffern lässt)
//   bodyweight_loaded -> Zusatzgewicht + Wdh. (Klimmzüge, Dips)
// seedWeightKg: Startgewicht laut Plan — wird beim ersten Laden dieser Plan-Version als Zielvorschlag übernommen,
// damit die Trainingsansicht auch vor dem ersten geloggten Satz sinnvolle Werte zeigt (siehe store.js -> adoptPlanIfNeeded).
// progression.strategy siehe progression.js für die jeweilige Berechnung.
// progression.role "main" = Übung mit explizitem Wochenziel im Plan (Dashboard-Trend + Stagnations-Check).

export const PLAN_ID = "home-gym-v2";

export const PLAN = {
  id: PLAN_ID,
  name: "Home Gym Split",
  cycle: 2,
  cycleLabel: "Zyklus 2",
  days: [
    {
      id: "tag1-push",
      dayNumber: 1,
      title: "Push",
      subtitle: "Brust • Schulter • Trizeps • Powerbuilding",
      accent: "orange",
      warmup: {
        minutes: "8",
        items: [
          "5 Min Airbike (leicht, Puls ~120)",
          "10× Shoulder Pass-Throughs • 10× Band Pull-Aparts",
          "2 Aufwärmsätze Bankdrücken: 60 kg × 5, 75 kg × 3",
          "10× Push-Up (langsam, kontrolliert)",
        ],
      },
      exercises: [
        {
          id: "push-bankdruecken",
          badge: "1",
          badgeColor: "orange",
          name: "Bankdrücken (Langhantel)",
          cue: "KRAFT: Start 82,5 kg — Ziel: 90+ kg über 6 Wochen",
          footerNote: "RPE 9 letzter Satz — nur volle Wdh., keine halben",
          loadType: "barbell",
          seedWeightKg: 82.5,
          pauseLabel: "3 Min",
          pauseSeconds: 180,
          movements: [{ sets: 5, repType: "range", repMin: 4, repMax: 5 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "main" },
        },
        {
          id: "push-incline-flyes",
          badge: "2",
          badgeColor: "orange",
          name: "Incline Kurzhantel Flyes",
          cue: "Neue Übung — 30°, weiter Bogen, voller Stretch",
          footerNote: "KH 14–16 kg; Ellenbogen leicht gebeugt, Brust dehnen",
          loadType: "dumbbell",
          seedWeightKg: 15,
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "range", repMin: 12, repMax: 15 }],
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "push-military-press",
          badge: "3",
          badgeColor: "purple",
          name: "Military Press sitzend (LH)",
          cue: "Sitzend statt stehend — mehr Schulter-Isolation",
          footerNote: "Start 36 kg; Stange vor Kinn absenken, explosiv drücken",
          loadType: "barbell",
          seedWeightKg: 36,
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 4, repType: "range", repMin: 6, repMax: 8 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "push-seitheben-facepull",
          badge: "4",
          badgeColor: "purple",
          name: "Kurzhantel Seitheben (Supersatz*)",
          cue: "*direkt gefolgt von Face Pulls mit Band — kein Pause",
          footerNote: "KH 10 kg + Band; hintere Schulter + lateraler Kopf",
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [
            { name: "Seitliches Heben", sets: 4, repType: "fixed", repFixed: 15, loadType: "dumbbell" },
            { name: "Face Pull mit Band", sets: 4, repType: "fixed", repFixed: 15, loadType: "bodyweight" },
          ],
          loadType: "dumbbell",
          seedWeightKg: 10,
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "push-cg-bench",
          badge: "5",
          badgeColor: "green",
          name: "Close-Grip Bankdrücken (LH)",
          cue: "Neue Grundübung Trizeps statt Dips",
          footerNote: "Start 60 kg; Ellenbogen eng am Körper, tief absenken",
          loadType: "barbell",
          seedWeightKg: 60,
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 4, repType: "range", repMin: 6, repMax: 8 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "push-trizeps-pushdown",
          badge: "6",
          badgeColor: "green",
          name: "Trizeps Pushdown (Band/Seilzug)",
          cue: "Isolationsfinisher — langsam, volle Streckung",
          footerNote: "Ellenbogen fixiert; kurze Pause bei voller Streckung",
          loadType: "bodyweight",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "fixed", repFixed: 15 }],
          progression: { strategy: "reps-then-weight", role: "assist" },
        },
      ],
      progressionNotes: [
        "Bankdrücken: Ziel +5 kg in 6 Wochen (→ 90 kg × 4–5).",
        "Incline Flyes + CG-Bench: neue Reize für Brust & Trizeps.",
        "RPE Grundübungen: 8–9 • Assistenz: 7–8 (kontrolliert)",
      ],
    },

    {
      id: "tag2-pull",
      dayNumber: 2,
      title: "Pull",
      subtitle: "Rücken • Bizeps • Hintere Schulter • Powerbuilding",
      accent: "orange",
      warmup: {
        minutes: "8",
        items: [
          "5 Min Rudergerät (leicht, Technikfokus)",
          "10× Dead Hang • 10× Scapular Pull-Ups",
          "2 Aufwärmsätze Klimmzug: 3× KG, dann 3× +5 kg",
          "10× Band Face Pull (Schultern vorbereiten)",
        ],
      },
      exercises: [
        {
          id: "pull-klimmzuege",
          badge: "1",
          badgeColor: "orange",
          name: "Gewichtete Klimmzüge",
          cue: "KRAFT: Start +10 kg — Ziel: +15 kg über 6 Wochen",
          footerNote: "Untergriff; volle Streckung unten, Kinn über Stange",
          loadType: "bodyweight_loaded",
          seedWeightKg: 10,
          pauseLabel: "3 Min",
          pauseSeconds: 180,
          movements: [{ sets: 5, repType: "range", repMin: 4, repMax: 5 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "main" },
        },
        {
          id: "pull-pendlay-row",
          badge: "2",
          badgeColor: "orange",
          name: "Pendlay Row (Langhantel)",
          cue: "Beibehaltung als Grundübung — Gewicht steigern",
          footerNote: "Start 65 kg; Stab berührt Boden, explosiv ziehen",
          loadType: "barbell",
          seedWeightKg: 65,
          pauseLabel: "2,5 Min",
          pauseSeconds: 150,
          movements: [{ sets: 4, repType: "range", repMin: 4, repMax: 6 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "pull-chest-supported-row",
          badge: "3",
          badgeColor: "purple",
          name: "Kurzhantel Chest-Supported Row",
          cue: "Neue Übung: auf Bank legen (30°), kein Schwung möglich",
          footerNote: "KH 2× 20 kg; reine Rückenarbeit, keine Körperbewegung",
          loadType: "dumbbell",
          seedWeightKg: 20,
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [{ sets: 3, repType: "range", repMin: 12, repMax: 15 }],
          progression: { strategy: "range-weight", incrementKg: 2, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "pull-facepull",
          badge: "4",
          badgeColor: "purple",
          name: "Facepull mit Band (an Rack)",
          cue: "Hintere Schulter + Rotatorenmanschette",
          footerNote: "Band auf Augenhöhe; Ellenbogen hoch, auseinander ziehen",
          loadType: "bodyweight",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "fixed", repFixed: 20 }],
          progression: { strategy: "reps-then-weight", role: "assist" },
        },
        {
          id: "pull-ez-curl",
          badge: "5",
          badgeColor: "green",
          name: "EZ-Stangen Curl (Untergriff)",
          cue: "Grundübung Bizeps — schwerer als Zyklus 1",
          footerNote: "Start 38 kg; 3 Sek negativ, voll strecken unten",
          loadType: "barbell",
          seedWeightKg: 38,
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [{ sets: 4, repType: "range", repMin: 6, repMax: 8 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "pull-incline-curl",
          badge: "6",
          badgeColor: "green",
          name: "Incline Kurzhantel Curl",
          cue: "Neue Übung: auf geneigter Bank, max. Stretch",
          footerNote: "KH 12–14 kg; langer Bizepskopf, kein Schwung möglich",
          loadType: "dumbbell",
          seedWeightKg: 13,
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "range", repMin: 12, repMax: 15 }],
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
      ],
      progressionNotes: [
        "Klimmzüge: Ziel +15 kg × 4–5 in Woche 6.",
        "Chest-Supported Row: eliminiert Schwung — reiner Rücken.",
        "Incline Curl: Stretch-Position = max. Muskelreiz für Bizeps.",
      ],
    },

    {
      id: "tag3-metabolic",
      dayNumber: 3,
      title: "Metabolic",
      subtitle: "Fettverbrennung • Kondition • Ganzkörper",
      accent: "orange",
      isCircuitDay: true,
      warmup: {
        minutes: "8",
        items: [
          "3 Min Airbike (mittleres Tempo aufbauen)",
          "10× World's Greatest Stretch (pro Seite)",
          "10× Goblet Squat mit KB 16 kg • 10× Hip Hinge mit Stab",
          "5× Box Jump (leicht, Aktivierung)",
        ],
      },
      intervalBlock: {
        id: "block-a",
        label: "Airbike Intervalle",
        cue: "25 Sek Sprint (90–95%) / 35 Sek locker × 12 Runden",
        footerNote: "Intensiviert vs. Zyklus 1 — Watt-Zahl pro Sprint notieren",
        totalLabel: "~14 Min",
        baseRounds: 12,
        workSeconds: 25,
        restSeconds: 35,
        advanced: { afterSessions: 3, badge: "Wk4+", rounds: 14, workSeconds: 25, restSeconds: 35 },
      },
      circuitBlock: {
        id: "block-b",
        rounds: 3,
        roundRestSeconds: 90,
        exercises: [
          { id: "metabolic-hip-thrust", badge: "B1", badgeColor: "orange", name: "Hip Thrust (Langhantel)", cue: "Ersetzt KB Swing (Bizepssehne) — Schultern auf Bank, Pause + Squeeze oben", loadLabel: "40 kg", workSeconds: 45 },
          { id: "metabolic-burpee-box-jump", badge: "B2", badgeColor: "purple", name: "Burpee Box Jump", cue: "Burpee auf Boden, dann Box Jump — explosiv bleiben", loadLabel: "Box", workSeconds: 45 },
          { id: "metabolic-clean-press", badge: "B3", badgeColor: "orange", name: "KB Clean & Press (alternierend)", cue: "Sauber cleanen, volle Hüftstreckung beim Drücken", loadLabel: "KB 16 kg", workSeconds: 45 },
          { id: "metabolic-renegade-row", badge: "B4", badgeColor: "green", name: "Renegade Row", cue: "Core bretthart, keine Rotation — je Seite zählt", loadLabel: "KH 17,5 kg", workSeconds: 45 },
          { id: "metabolic-jump-rope", badge: "B5", badgeColor: "green", name: "Springseil (schnell)", cue: "B1→B2→B3→B4→B5 ohne Pause, dann 90 Sek, × 3", loadLabel: "Seil", workSeconds: 45 },
        ],
      },
      finisher: null,
      exercises: [],
      progressionNotes: [
        "Circuit B: B1→B2→B3→B4→B5 ohne Pause, dann 90 Sek × 3.",
        "Hip Thrust ersetzt KB Swing (Bizepssehne schonen) — Burpee Box Jump ersetzt einfachen Box Jump für mehr Intensität.",
      ],
    },

    {
      id: "tag4-beine",
      dayNumber: 4,
      title: "Beine",
      subtitle: "Quadrizeps • Ischio • Gesäß • Powerbuilding",
      accent: "orange",
      warmup: {
        minutes: "8–10",
        items: [
          "5 Min Rudergerät (mittleres Tempo)",
          "10× Bodyweight Squat tief • 10× Glute Bridge",
          "2 Aufwärmsätze Kniebeuge: 60 kg × 5, 75 kg × 3",
          "10× Leg Swing vor/zurück + seitlich (pro Seite)",
        ],
      },
      exercises: [
        {
          id: "beine-kniebeuge",
          badge: "1",
          badgeColor: "orange",
          name: "Kniebeuge (Langhantel, Low Bar)",
          cue: "KRAFT: Start 82,5 kg — Ziel: 92,5 kg in Woche 6",
          footerNote: "Oberschenkel parallel+, Rücken neutral, RPE 9 letzter Satz",
          loadType: "barbell",
          seedWeightKg: 82.5,
          pauseLabel: "3 Min",
          pauseSeconds: 180,
          movements: [{ sets: 5, repType: "range", repMin: 4, repMax: 5 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 1.5, role: "main" },
        },
        {
          id: "beine-rdl",
          badge: "2",
          badgeColor: "orange",
          name: "Romanian Deadlift (Langhantel)",
          cue: "Schwerer als Zyklus 1 — Tempo halten",
          footerNote: "Start 67,5 kg; 3 Sek negativ, Ischios maximal dehnen",
          loadType: "barbell",
          seedWeightKg: 67.5,
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 4, repType: "range", repMin: 6, repMax: 8 }],
          progression: { strategy: "tempo-focus", role: "assist" },
        },
        {
          id: "beine-bulgarian-split-squat",
          badge: "3",
          badgeColor: "purple",
          name: "Bulgarischer Split Squat (KH)",
          cue: "Neue Übung — hinteres Bein auf Bank (pro Seite)",
          footerNote: "KH 2× 16–18 kg; Knie vorne nicht über Zehen, tief",
          loadType: "dumbbell",
          seedWeightKg: 17,
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 3, repType: "range", repMin: 8, repMax: 10 }],
          progression: { strategy: "range-weight", incrementKg: 2, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "beine-hip-thrust",
          badge: "4",
          badgeColor: "purple",
          name: "Hip Thrust (Langhantel)",
          cue: "Ersetzt KB Swing (Bizepssehne!) — stärkstes Gesäß-Tool",
          footerNote: "Start 40 kg; Schultern auf Bank, Pause + Squeeze oben",
          loadType: "barbell",
          seedWeightKg: 40,
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [{ sets: 3, repType: "range", repMin: 8, repMax: 10 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "beine-nordic-curl",
          badge: "5",
          badgeColor: "green",
          name: "Nordic Hamstring Curl (auf Bank)",
          cue: "Neue Übung — Füße unter Bank klemmen, langsam senken",
          footerNote: "Exzentrisch = stärkster Reiz für Ischios; sehr langsam",
          loadType: "bodyweight",
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 2, repType: "range", repMin: 5, repMax: 8 }],
          progression: { strategy: "reps-then-weight", role: "assist" },
        },
      ],
      progressionNotes: [
        "Kniebeuge: Ziel 92,5 kg × 4–5 in Woche 6 (aktuell 85 kg × 8).",
        "Bulg. Split Squat: einseitig = Schwächen ausgleichen + mehr Tiefe.",
        "Nordic Curl: härteste Ischio-Übung — langsam starten, max. 5 Wdh.",
      ],
    },

    {
      id: "tag5-arme",
      dayNumber: 5,
      title: "Arme",
      subtitle: "Bizeps • Trizeps • Unterarme • Volumen-Spezial",
      accent: "orange",
      warmup: {
        minutes: "6",
        items: [
          "3 Min Airbike (locker)",
          "2× 12 Wdh. EZ-Curl ohne Gewicht (Technik)",
          "2× 12 Wdh. Overhead Extension ohne Gewicht",
          "Dead Hang 30 Sek + 10× Scapular Pull-Ups",
        ],
      },
      exercises: [
        {
          id: "arme-ez-curl-superset",
          badge: "A1",
          badgeColor: "orange",
          name: "EZ-Stangen Curl (Untergriff)",
          cue: "Superset A — direkt zu A2, dann 90 Sek Pause",
          footerNote: "Start 40 kg; 3 Sek negativ, 2 Sek oben halten",
          loadType: "barbell",
          seedWeightKg: 40,
          pauseLabel: "→ A2",
          chainNext: "arme-skull-crushers",
          movements: [{ sets: 4, repType: "range", repMin: 6, repMax: 8 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "arme-skull-crushers",
          badge: "A2",
          badgeColor: "orange",
          name: "Skull Crushers (EZ-Stange)",
          cue: "Trizeps-Grundübung neu auf Arm-Tag",
          footerNote: "Start 35 kg; Ellenbogen fixiert, langsam senken",
          loadType: "barbell",
          seedWeightKg: 35,
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 4, repType: "range", repMin: 8, repMax: 10 }],
          progression: { strategy: "range-weight", incrementKg: 1.25, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "arme-incline-curl-45",
          badge: "B1",
          badgeColor: "purple",
          name: "Incline KH Curl (Bank 45°)",
          cue: "Superset B — langer Bizepskopf, kein Schwung",
          footerNote: "KH 12–14 kg; volle Streckung, Arme hängen lassen",
          loadType: "dumbbell",
          seedWeightKg: 13,
          pauseLabel: "→ B2",
          chainNext: "arme-overhead-triceps-kh",
          movements: [{ sets: 3, repType: "range", repMin: 10, repMax: 12 }],
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "arme-overhead-triceps-kh",
          badge: "B2",
          badgeColor: "purple",
          name: "Overhead Trizeps Extension (KH)",
          cue: "Einarmig oder beidhändig, langer Kopf",
          footerNote: "KH 16–18 kg; Ellenbogen nah am Kopf, tief senken",
          loadType: "dumbbell",
          seedWeightKg: 17,
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 3, repType: "range", repMin: 10, repMax: 12 }],
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "arme-hammer-curl",
          badge: "C1",
          badgeColor: "green",
          name: "Hammer Curl (KH)",
          cue: "Superset C — Brachialis + Unterarmvolumen",
          footerNote: "KH 14–16 kg; Neutralgriff, kein Schwung",
          loadType: "dumbbell",
          seedWeightKg: 15,
          pauseLabel: "→ C2",
          chainNext: "arme-band-pushdown",
          movements: [{ sets: 3, repType: "range", repMin: 12, repMax: 15 }],
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "arme-band-pushdown",
          badge: "C2",
          badgeColor: "green",
          name: "Band Trizeps Pushdown",
          cue: "Hohe Wdh. als Pump-Finisher",
          footerNote: "Ellenbogen fixiert; kurze Pause bei Streckung unten",
          loadType: "bodyweight",
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [{ sets: 3, repType: "range", repMin: 15, repMax: 20 }],
          progression: { strategy: "reps-then-weight", role: "assist" },
        },
      ],
      progressionNotes: [
        "Skull Crushers: neuer schwerer Trizeps-Anker statt Dips.",
        "Incline Curl: Stretch-Position maximiert langen Bizepskopf.",
        "Ziel: Oberarm-Umfang messen vor + nach Zyklus 2.",
      ],
    },
  ],
};

export function getDay(dayId) {
  return PLAN.days.find((d) => d.id === dayId);
}

export function getExercise(dayId, exerciseId) {
  const day = getDay(dayId);
  return day?.exercises.find((e) => e.id === exerciseId);
}

export function allStrengthExercises() {
  return PLAN.days.flatMap((d) => d.exercises.map((e) => ({ ...e, dayId: d.id, dayTitle: d.title })));
}
