// Basis-Trainingsplan (Home Gym) — Ausgangszustand für den jeweiligen Plan.
// Wird zur Laufzeit durch geloggte Trainings automatisch fortgeschrieben (siehe progression.js -> exerciseTargets in store.js).
// repType: "range" (Wdh.-Spanne) | "fixed" (feste Wdh./Zahl) | "perSide" (Wdh. pro Seite) | "max" (bis Versagen) | "time" (Sekunden) | "special21"
// loadType steuert die Eingabefelder in der Trainingsansicht:
//   barbell/dumbbell/kettlebell/cable -> Gewicht + Wdh. je Satz
//   bodyweight -> nur Wdh. (z. B. Bänder, Core)
//   bodyweight_loaded -> Zusatzgewicht + Wdh. (Klimmzüge)
// seedWeightKg: Startgewicht laut Plan — wird beim ersten Laden dieser Plan-Version als Zielvorschlag übernommen (store.js -> adoptPlanIfNeeded).
// movement.seedWeightKg: Startgewicht für weitere Bewegungen einer Karte mit mehreren Bewegungen (die erste nutzt seedWeightKg der Übung).
// progression.role "main" = Übung mit explizitem Wochenziel im Plan (Dashboard-Trend + Stagnations-Check).
// Einträge mit type: "interval" | "circuit" | "finisher" sind Spezialblöcke (Timer + Ergebnis-Eingabe) und werden nicht progressiert.
// Übungs-IDs bleiben über Pläne hinweg stabil, wenn es dieselbe Übung ist — so bleibt die Historie (Vorwochenwerte) erhalten.

export const PLAN_ID = "home-gym-v4-zyklus3";

export const PLAN = {
  id: PLAN_ID,
  name: "Home Gym Split",
  cycle: 3,
  cycleLabel: "Zyklus 3",
  startDate: "2026-10-05",
  overview: {
    strategy: "Zyklus 3 (ab 05.10.2026): weniger Volumen, höhere Qualität — RPE 9 bei den Grundübungen. Neu: Kabelzug-Übungen und Core am Ende von Pull und Arme.",
  },
  changeNotes: [
    {
      scope: "plan",
      title: "Zyklus 3 gestartet (ab 05.10.2026)",
      reason: "Wieder 5-Tage-Split mit weniger Sätzen und höherer Qualität; neue Startgewichte (Bankdrücken 90 kg, Kniebeuge 97,5 kg).",
      kind: "note",
    },
    {
      scope: "exercise",
      dayId: "tag3-metabolic",
      title: "Metabolic+: Türkisches Get-Up und Wall Ball im Circuit",
      reason: "Regen-schonend; Airbike jetzt 30/30 × 12, kein Goblet Squat, damit die Beine für Do frisch bleiben.",
      kind: "swap",
    },
  ],
  days: [
    {
      id: "tag1-push",
      dayNumber: 1,
      title: "Push",
      subtitle: "Brust • Trizeps • Schulter",
      accent: "orange",
      warmup: {
        minutes: "8",
        items: [
          "5 Min Airbike (leicht, Puls ~120)",
          "10× Shoulder Pass-Throughs • 10× Band Pull-Aparts",
          "2 Aufwärmsätze Bankdrücken: 70 kg × 4, 82,5 kg × 2",
          "10× Push-Up (langsam) • 10× Scapular Push-Up",
        ],
      },
      exercises: [
        {
          id: "push-bankdruecken",
          badge: "1",
          badgeColor: "orange",
          name: "Bankdrücken (Langhantel)",
          cue: "KRAFT — Start 90 kg, Ziel: 97,5 kg Woche 6",
          footerNote: "RPE 9; progressive Überlastung, hohe Qualität",
          loadType: "barbell",
          seedWeightKg: 90,
          pauseLabel: "3 Min",
          pauseSeconds: 180,
          movements: [{ sets: 4, repType: "range", repMin: 4, repMax: 6 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "main" },
        },
        {
          id: "push-kh-bankdruecken",
          badge: "2",
          badgeColor: "orange",
          name: "KH Bankdrücken (Neutralgriff)",
          cue: "Neuer Reiz — Neutralgriff schont Schulter",
          footerNote: "KH 2× 22,5 kg; 3 Sek senken, voller Stretch",
          loadType: "dumbbell",
          seedWeightKg: 22.5,
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [{ sets: 3, repType: "range", repMin: 8, repMax: 12 }],
          progression: { strategy: "range-weight", incrementKg: 2, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "push-military-press-stehend",
          badge: "3",
          badgeColor: "purple",
          name: "Military Press stehend (LH)",
          cue: "Start 42,5 kg — Ziel 47,5 kg Woche 6",
          footerNote: "Core bretthart, kein Hohlkreuz; explosiv drücken",
          loadType: "barbell",
          seedWeightKg: 42.5,
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 3, repType: "range", repMin: 6, repMax: 8 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "push-cable-fly",
          badge: "4",
          badgeColor: "purple",
          name: "Einarmiges Cable Fly (Seilzug)",
          cue: "Wechselseitig — eine Seite, dann andere",
          footerNote: "Seilzug auf Brusthöhe; langer Bogen, Brust dehnen",
          loadType: "cable",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "perSide", repFixed: 12 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "push-cg-bench-dips",
          badge: "5",
          badgeColor: "green",
          name: "CG Bench + Dips (Supersatz)",
          cue: "CG Bench 68 kg × 6 direkt zu Dips",
          footerNote: "68 kg × 6, dann Dips bis Versagen; Trizeps pur",
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          loadType: "barbell",
          seedWeightKg: 68,
          movements: [
            { name: "CG Bench", sets: 3, repType: "fixed", repFixed: 6, loadType: "barbell" },
            { name: "Dips", sets: 3, repType: "max", loadType: "bodyweight" },
          ],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "push-seitheben-sitzend",
          badge: "6a",
          badgeColor: "green",
          name: "Seitheben sitzend (KH)",
          cue: "Superset — sitzend = kein Schwung möglich",
          footerNote: "KH 12,5 kg seitlich",
          loadType: "dumbbell",
          seedWeightKg: 12.5,
          pauseLabel: "→ 6b",
          chainNext: "push-frontheben",
          movements: [{ sets: 3, repType: "fixed", repFixed: 12 }],
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "push-frontheben",
          badge: "6b",
          badgeColor: "green",
          name: "Frontales Heben (KH)",
          cue: "Superset — sitzend = kein Schwung möglich",
          footerNote: "KH 10 kg frontal",
          loadType: "dumbbell",
          seedWeightKg: 10,
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "fixed", repFixed: 10 }],
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
      ],
      progressionNotes: [
        "Bankdrücken: Start 90 kg → Ziel 97,5 kg Woche 6.",
        "Military Press: Start 42,5 kg → Ziel 47,5 kg Woche 6.",
        "Weniger Volumen, höhere Qualität — RPE 9 bei Grundübungen.",
      ],
    },

    {
      id: "tag2-pull",
      dayNumber: 2,
      title: "Pull + Core",
      subtitle: "Rücken • Bizeps • Hintere Schulter • Core",
      accent: "orange",
      warmup: {
        minutes: "8",
        items: [
          "5 Min Rudergerät (leicht, Technikfokus)",
          "10× Dead Hang • 10× Scapular Pull-Ups",
          "2 Aufwärmsätze Klimmzug: 3× Körpergewicht, 3× +7,5 kg",
          "10× Kabel Face Pull leicht (Schultern vorbereiten)",
        ],
      },
      exercises: [
        {
          id: "pull-klimmzuege",
          badge: "1",
          badgeColor: "orange",
          name: "Gewichtete Klimmzüge",
          cue: "KRAFT — Start +12,5 kg, Ziel: +17,5 kg Woche 6",
          footerNote: "Untergriff; volle Streckung unten, Kinn über Stange",
          loadType: "bodyweight_loaded",
          seedWeightKg: 12.5,
          pauseLabel: "3 Min",
          pauseSeconds: 180,
          movements: [{ sets: 4, repType: "range", repMin: 4, repMax: 6 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "main" },
        },
        {
          id: "pull-yates-row",
          badge: "2",
          badgeColor: "orange",
          name: "Yates Row (LH, Untergriff)",
          cue: "Start 80 kg — Ziel: 87,5 kg Woche 6",
          footerNote: "30–45° Oberkörper; Ellenbogen eng, explosiv ziehen",
          loadType: "barbell",
          seedWeightKg: 80,
          pauseLabel: "2 Min",
          pauseSeconds: 120,
          movements: [{ sets: 4, repType: "range", repMin: 6, repMax: 8 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "pull-kabel-rudern",
          badge: "3",
          badgeColor: "purple",
          name: "Kabel Rudern (Seilzug unten)",
          cue: "Horizontaler Zug — Schulterblätter einziehen",
          footerNote: "V-Griff oder Seilgriff; Schulterblätter zusammenziehen",
          loadType: "cable",
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [{ sets: 3, repType: "range", repMin: 10, repMax: 12 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "pull-facepull-ez-zottman",
          badge: "4",
          badgeColor: "purple",
          name: "Kabel Face Pull • EZ Curl • Zottman Curl",
          cue: "3× Face Pull (15–20) + 3× EZ 6–8 + 3× Zottman 10–12",
          footerNote: "Face Pull: Seilgriff Augenhöhe • EZ Start 38 kg • Zottman KH 12–14 kg",
          pauseLabel: "60–75 Sek",
          pauseSeconds: 75,
          loadType: "cable",
          movements: [
            { name: "Face Pull", sets: 3, repType: "range", repMin: 15, repMax: 20, loadType: "cable" },
            { name: "EZ Curl", sets: 3, repType: "range", repMin: 6, repMax: 8, loadType: "barbell", seedWeightKg: 38 },
            { name: "Zottman Curl", sets: 3, repType: "range", repMin: 10, repMax: 12, loadType: "dumbbell", seedWeightKg: 13 },
          ],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "pull-cable-crunch",
          badge: "5",
          badgeColor: "green",
          name: "Cable Crunch (Knieend, Seilzug oben)",
          cue: "Core — Kabelzug von oben, Stirn Richtung Knie",
          footerNote: "Gewicht so wählen, dass Bauch zieht, nicht Hüfte",
          loadType: "cable",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "range", repMin: 10, repMax: 15 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "pull-hanging-raise",
          badge: "6",
          badgeColor: "green",
          name: "Hanging Knee / Leg Raise (Klimmzugstange)",
          cue: "Core — Knie oder gestreckte Beine heben",
          footerNote: "Kontrolliert heben und senken; kein Schwung",
          loadType: "bodyweight",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "range", repMin: 8, repMax: 15 }],
          progression: { strategy: "reps-then-weight", role: "assist" },
        },
      ],
      progressionNotes: [
        "Klimmzüge: Ziel +17,5 kg × 4–6 in Woche 6.",
        "Yates Row: Start 80 kg → Ziel 87,5 kg Woche 6.",
        "Core am Ende: Cable Crunch + Hanging Raise schließen ab.",
      ],
    },

    {
      id: "tag3-metabolic",
      dayNumber: 3,
      title: "Metabolic+",
      subtitle: "Kondition • Fettverbrennung • Ganzkörper • Regen-schonend",
      accent: "orange",
      warmup: {
        minutes: "8",
        items: [
          "3 Min Airbike (mittleres Tempo aufbauen)",
          "10× World's Greatest Stretch (pro Seite)",
          "5× Türkisches Get-Up sehr leicht (Technik)",
          "10× Mountain Climbers langsam (Aktivierung)",
        ],
      },
      exercises: [
        {
          type: "interval",
          id: "block-a",
          badge: "A",
          badgeColor: "orange",
          label: "Airbike 30/30 × 12",
          cue: "30 Sek Sprint (max) / 30 Sek locker — Peak 204 W schlagen",
          footerNote: "Watt-Peak notieren; 30/30 intensiver als 25/35",
          totalLabel: "~14 Min",
          baseRounds: 12,
          workSeconds: 30,
          restSeconds: 30,
          advanced: { afterSessions: 3, badge: "Wk4+", rounds: 14 },
        },
        {
          type: "circuit",
          id: "block-b",
          badge: "B",
          rounds: 3,
          roundRestSeconds: 90,
          exercises: [
            { id: "metabolic-get-up", badge: "B1", badgeColor: "orange", name: "Türkisches Get-Up (KB)", cue: "Langsam + kontrolliert; Blick auf KB-Hand fixiert", loadLabel: "KB 16 kg", workSeconds: 45 },
            { id: "metabolic-wall-ball", badge: "B2", badgeColor: "purple", name: "Wall Ball (Medizinball 12 kg)", cue: "Squat tief, Ball auf ~3 m Zielpunkt, fangen", loadLabel: "MB 12 kg", workSeconds: 45 },
            { id: "metabolic-renegade-row", badge: "B3", badgeColor: "purple", name: "Renegade Row", cue: "Core bretthart, keine Rotation — je Seite zählt", loadLabel: "KH 20 kg", workSeconds: 45 },
            { id: "metabolic-mountain-climbers", badge: "B4", badgeColor: "green", name: "Mountain Climbers", cue: "Hüfte tief, schnelles Tempo, Core aktiv halten", loadLabel: "KG", workSeconds: 45 },
            { id: "metabolic-jump-rope", badge: "B5", badgeColor: "green", name: "Springseil (schnell)", cue: "B1→B2→B3→B4→B5 ohne Pause, dann 90 Sek, × 3", loadLabel: "Seil", workSeconds: 45 },
          ],
        },
        {
          type: "finisher",
          id: "metabolic-finisher",
          label: "Ruder-Finisher",
          detail: "5 × 250 m mit 60 Sek Pause — Ziel <49 Sek.",
          reps: 5,
          distanceLabel: "250 m",
          targetSeconds: 49,
          pauseSeconds: 60,
        },
      ],
      progressionNotes: [
        "Circuit B: B1→B2→B3→B4→B5 ohne Pause, dann 90 Sek × 3 Runden.",
        "Ruder-Finisher: 5 × 250 m mit 60 Sek Pause — Ziel <49 Sek.",
        "Kein Goblet Squat: schont Beine für schweres Beintraining Do.",
      ],
    },

    {
      id: "tag4-beine",
      dayNumber: 4,
      title: "Beine",
      subtitle: "Kraft • Posterior Chain • Unilateral",
      accent: "orange",
      warmup: {
        minutes: "8",
        items: [
          "5 Min Rudergerät (mittleres Tempo)",
          "10× Bodyweight Squat tief • 10× Glute Bridge",
          "2 Aufwärmsätze Kniebeuge: 60 kg × 4, 82,5 kg × 2",
          "10× Leg Swing vor/zurück + seitlich (pro Seite)",
        ],
      },
      exercises: [
        {
          id: "beine-kniebeuge",
          badge: "1",
          badgeColor: "orange",
          name: "Kniebeuge (Langhantel, Low Bar)",
          cue: "KRAFT — Start 97,5 kg, Ziel: 105 kg Woche 6",
          footerNote: "Oberschenkel parallel+; RPE 9, hohe Qualität",
          loadType: "barbell",
          seedWeightKg: 97.5,
          pauseLabel: "3 Min",
          pauseSeconds: 180,
          movements: [{ sets: 4, repType: "range", repMin: 4, repMax: 6 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 1.5, role: "main" },
        },
        {
          id: "beine-einbeiniger-rdl",
          badge: "2",
          badgeColor: "orange",
          name: "Einbeiniger RDL (KH)",
          cue: "Tiefer Stretch — Schwächen ausgleichen",
          footerNote: "KH 20–22,5 kg; freie Hand leicht abstützen",
          loadType: "dumbbell",
          seedWeightKg: 20,
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 3, repType: "perSide", repFixed: 8 }],
          progression: { strategy: "range-weight", incrementKg: 2, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "beine-hack-squat",
          badge: "3",
          badgeColor: "purple",
          name: "Hack Squat (LH hinter Rücken)",
          cue: "Quad-Fokus — Fersen leicht erhöht",
          footerNote: "Start 40 kg; Stange hinter Oberschenkeln, Rücken gerade",
          loadType: "barbell",
          seedWeightKg: 40,
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 3, repType: "range", repMin: 8, repMax: 10 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "beine-hip-thrust",
          badge: "4",
          badgeColor: "purple",
          name: "Hip Thrust (Langhantel)",
          cue: "Start 50 kg — Ziel 65 kg Woche 6",
          footerNote: "Schultern auf Bank; Pause + maximaler Squeeze oben",
          loadType: "barbell",
          seedWeightKg: 50,
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [{ sets: 3, repType: "range", repMin: 6, repMax: 8 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "beine-bulgarian-split-squat",
          badge: "5",
          badgeColor: "green",
          name: "Bulg. Split Squat (KH)",
          cue: "Hinteres Bein auf Bank, tief",
          footerNote: "KH 2× 17,5–20 kg; hinteres Bein höher = mehr Stretch",
          loadType: "dumbbell",
          seedWeightKg: 17.5,
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 3, repType: "perSide", repFixed: 8 }],
          progression: { strategy: "range-weight", incrementKg: 2, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "beine-nordic-curl",
          badge: "6",
          badgeColor: "green",
          name: "Nordic Hamstring Curl",
          cue: "4 Sek senken — stärkster Ischio-Reiz",
          footerNote: "Sehr langsam; Hände kurz abstützen wenn nötig",
          loadType: "bodyweight",
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 3, repType: "range", repMin: 6, repMax: 8 }],
          progression: { strategy: "reps-then-weight", role: "assist" },
        },
      ],
      progressionNotes: [
        "Kniebeuge: Start 97,5 kg → Ziel 105 kg Woche 6.",
        "Hip Thrust: Start 50 kg → Ziel 65 kg Woche 6.",
        "Weniger Sätze, höhere Qualität — Do nach Mi Metabolic.",
      ],
    },

    {
      id: "tag5-arme",
      dayNumber: 5,
      title: "Schulter + Arme + Core",
      subtitle: "Schulter • Bizeps • Trizeps • Core",
      accent: "orange",
      warmup: {
        minutes: "8",
        items: [
          "3 Min Airbike (locker)",
          "2× 12 Wdh. Schulterkreisen mit Stab",
          "2× 12 Wdh. EZ Curl ohne Gewicht + Kabel Face Pull × 15",
          "Dead Hang 30 Sek + 10× Scapular Pull-Ups",
        ],
      },
      exercises: [
        {
          id: "schulter-arnold-press",
          badge: "1",
          badgeColor: "orange",
          name: "Arnold Press (KH, sitzend)",
          cue: "Alle Schulterköpfe — neuer Reiz",
          footerNote: "KH 18–20 kg; von Untergriff zu Übergriff drehen",
          loadType: "dumbbell",
          seedWeightKg: 18,
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 3, repType: "range", repMin: 8, repMax: 10 }],
          progression: { strategy: "range-weight", incrementKg: 2, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "arme-ez-curl-superset",
          badge: "2a",
          badgeColor: "orange",
          name: "EZ Curl",
          cue: "Superset — Grundübung Bi + Tri, schwerer als Z2",
          footerNote: "EZ 38–40 kg; 3 Sek negativ",
          loadType: "barbell",
          seedWeightKg: 40,
          pauseLabel: "→ 2b",
          chainNext: "arme-skull-crushers",
          movements: [{ sets: 3, repType: "range", repMin: 8, repMax: 10 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "arme-skull-crushers",
          badge: "2b",
          badgeColor: "orange",
          name: "Skull Crushers (EZ)",
          cue: "Superset — Grundübung Bi + Tri, schwerer als Z2",
          footerNote: "Skull 38–40 kg; 3 Sek negativ",
          loadType: "barbell",
          seedWeightKg: 38,
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 3, repType: "range", repMin: 8, repMax: 10 }],
          progression: { strategy: "range-weight", incrementKg: 1.25, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "schulter-seitheben-sitzend",
          badge: "3",
          badgeColor: "purple",
          name: "Seitheben sitzend (KH)",
          cue: "Sitzend = kein Schwung, sauberere Isolation",
          footerNote: "KH 12,5 kg; Ellenbogen leicht gebeugt, Pause oben",
          loadType: "dumbbell",
          seedWeightKg: 12.5,
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 4, repType: "range", repMin: 12, repMax: 15 }],
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "arme-incline-curl-45",
          badge: "4a",
          badgeColor: "purple",
          name: "Incline Curl (KH)",
          cue: "Superset — Stretch-Fokus Bi + Kabel Pushdown vom Cage",
          footerNote: "Incline KH 15 kg",
          loadType: "dumbbell",
          seedWeightKg: 15,
          pauseLabel: "→ 4b",
          chainNext: "arme-kabel-pushdown",
          movements: [{ sets: 3, repType: "range", repMin: 10, repMax: 15 }],
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "arme-kabel-pushdown",
          badge: "4b",
          badgeColor: "purple",
          name: "Kabel Trizeps Pushdown",
          cue: "Superset — Stretch-Fokus Bi + Kabel Pushdown vom Cage",
          footerNote: "Kabel Trizeps Pushdown oben",
          loadType: "cable",
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 3, repType: "range", repMin: 10, repMax: 15 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "arme-upright-hammer-unterarm",
          badge: "5",
          badgeColor: "green",
          name: "Upright Row + Hammer Curl + Unterarmgerät",
          cue: "2–3 Sätze je Übung — Finisher-Block",
          footerNote: "Upright Row EZ 30–35 kg • Hammer KH 22,5 kg • Unterarmgerät",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          loadType: "barbell",
          seedWeightKg: 30,
          movements: [
            { name: "Upright Row (EZ)", sets: 3, repType: "range", repMin: 10, repMax: 15, loadType: "barbell" },
            { name: "Hammer Curl (KH)", sets: 3, repType: "range", repMin: 10, repMax: 15, loadType: "dumbbell", seedWeightKg: 22.5 },
            { name: "Unterarmgerät", sets: 3, repType: "range", repMin: 10, repMax: 15, loadType: "cable" },
          ],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "schulter-core-finisher",
          badge: "6",
          badgeColor: "green",
          name: "Core: Cable Crunch + Hanging Knee Raise",
          cue: "3 × 10–15 Cable Crunch + 3 × 8–15 Hanging Raise",
          footerNote: "Kabelzug von oben für Crunch; Klimmzugstange für Raise",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          loadType: "cable",
          movements: [
            { name: "Cable Crunch", sets: 3, repType: "range", repMin: 10, repMax: 15, loadType: "cable" },
            { name: "Hanging Raise", sets: 3, repType: "range", repMin: 8, repMax: 15, loadType: "bodyweight" },
          ],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
      ],
      progressionNotes: [
        "Arnold Press + Seitheben 4×: Schultervolumen priorisiert.",
        "EZ Curl: Ziel 45 kg × 8–10 in Woche 6.",
        "Core-Block am Ende: Cable Crunch + Hanging Raise.",
      ],
    },
  ],
};

export function getDay(dayId) {
  return PLAN.days.find((d) => d.id === dayId);
}

export function getExercise(dayId, exerciseId) {
  const day = getDay(dayId);
  return day?.exercises.find((e) => e.id === exerciseId);
}

// Sucht eine Übung bzw. einen Block (auch Circuit-Übungen) im aktuellen Plan — für die Verlaufsanzeige.
// kind: "exercise" | "interval" | "finisher" | "circuitEx"
export function findExerciseById(exerciseId, preferDayId) {
  const days = [...PLAN.days].sort((a, b) => (b.id === preferDayId) - (a.id === preferDayId));
  for (const day of days) {
    for (const ex of day.exercises) {
      if (ex.id === exerciseId) return { ex, day, kind: ex.type || "exercise" };
      if (ex.type === "circuit") {
        const inner = ex.exercises.find((e) => e.id === exerciseId);
        if (inner) return { ex: inner, day, kind: "circuitEx" };
      }
    }
  }
  return null;
}

export function dayLabel(day) {
  return day.label || `Tag ${day.dayNumber}`;
}

export function dayShort(day) {
  return day.short || String(day.dayNumber);
}

export function allStrengthExercises() {
  return PLAN.days.flatMap((d) => d.exercises.filter((e) => !e.type).map((e) => ({ ...e, dayId: d.id, dayTitle: d.title })));
}
