// Basis-Trainingsplan (Home Gym) — Ausgangszustand.
// Wird zur Laufzeit ggf. durch Plan-Anpassungen (siehe store.js -> planOverrides) überschrieben.
// repType: "range" (Wdh.-Spanne) | "fixed" (feste Wdh./Zahl) | "perSide" (Wdh. pro Seite) | "time" (Sekunden Arbeit) | "special21" (21er-Methode)
// loadType steuert die Eingabefelder in der Trainingsansicht:
//   barbell/dumbbell/kettlebell -> Gewicht + Wdh. je Satz
//   bodyweight -> nur Wdh. (+ optionales Zusatzgewicht)
//   bodyweight_loaded -> Zusatzgewicht (oft 0) + Wdh., Fokus auf Wdh.-Progression bis Schwelle
// progression.strategy siehe progression.js für die jeweilige Berechnung.

export const PLAN_ID = "home-gym-v1";

export const PLAN = {
  id: PLAN_ID,
  name: "Home Gym Split",
  days: [
    {
      id: "tag1-push",
      dayNumber: 1,
      title: "Push",
      subtitle: "Brust • Schulter • Trizeps",
      accent: "orange",
      warmup: {
        minutes: "8–10",
        items: [
          "5 Min Airbike (leicht, Puls auf ~120)",
          "10× Arm Circles vorwärts + rückwärts",
          "10× Shoulder Pass-Throughs (Stab / Besenstiel)",
          "10× Push-Up • 10× Band Pull-Aparts",
        ],
      },
      exercises: [
        {
          id: "push-bankdruecken",
          badge: "1",
          badgeColor: "orange",
          name: "Bankdrücken (Langhantel)",
          cue: "Etwas breiter als schulterbreit",
          footerNote: "Progressiv steigern, letzten 2 Sätze RPE 8–9",
          loadType: "barbell",
          pauseLabel: "2–3 Min",
          pauseSeconds: 150,
          movements: [{ sets: 4, repType: "range", repMin: 6, repMax: 8 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "main" },
        },
        {
          id: "push-military-press",
          badge: "2",
          badgeColor: "orange",
          name: "Military Press stehend (LH)",
          cue: "Core aktiv, keine Rücküberstreckung",
          footerNote: "Stange nah am Gesicht vorbeiführen",
          loadType: "barbell",
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 3, repType: "range", repMin: 8, repMax: 10 }],
          progression: { strategy: "reps-then-weight", incrementKg: 2.5, role: "main" },
        },
        {
          id: "push-schraegbankdruecken",
          badge: "3",
          badgeColor: "purple",
          name: "Schrägbankdrücken (KH)",
          cue: "30–45° Neigung, obere Brust",
          footerNote: "Volle Streckung oben, kontrolliert senken",
          loadType: "dumbbell",
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [{ sets: 3, repType: "range", repMin: 10, repMax: 12 }],
          progression: { strategy: "range-weight", incrementKg: 2, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "push-seitheben",
          badge: "4",
          badgeColor: "purple",
          name: "Seitliches Heben (Kurzhantel)",
          cue: "Lateraler Deltamuskel, kein Schwung",
          footerNote: "Ellenbogen leicht gebeugt, Tempo halten",
          loadType: "dumbbell",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "range", repMin: 12, repMax: 15 }],
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "push-dips",
          badge: "5",
          badgeColor: "green",
          name: "Dips (Power Rack / Ringe)",
          cue: "Körper leicht vorgeneigt = mehr Brust",
          footerNote: "Bei Leichtigkeit: KH zwischen den Knien",
          loadType: "bodyweight_loaded",
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [{ sets: 3, repType: "range", repMin: 10, repMax: 12 }],
          progression: { strategy: "bodyweight-add-weight-at-threshold", thresholdReps: 12, addKg: 2.5, role: "assist" },
        },
        {
          id: "push-skullcrushers",
          badge: "6",
          badgeColor: "green",
          name: "Skull Crushers (EZ-Stange)",
          cue: "Auf Bank, Ellenbogen nah am Kopf",
          footerNote: "3 Sek negativ, kontrolliert absenken",
          loadType: "barbell",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "range", repMin: 10, repMax: 12 }],
          progression: { strategy: "range-weight", incrementKg: 1.25, cadenceWeeks: 2, role: "assist" },
        },
      ],
      progressionNotes: [
        "Bankdrücken: alle 2 Wochen +2,5 kg anstreben.",
        "OHP: +1–2 Wdh. pro Woche, dann Gewicht erhöhen.",
        "RPE Hauptübungen: 8–9 • Assistenz: 7–8",
      ],
    },

    {
      id: "tag2-pull",
      dayNumber: 2,
      title: "Pull",
      subtitle: "Rücken • Bizeps • Unterarme",
      accent: "orange",
      warmup: {
        minutes: "8–10",
        items: [
          "5 Min Rudergerät (leicht, Technikfokus)",
          "10× Dead Hang an Klimmzugstange (Schultern aktiv)",
          "10× Scapular Pull-Ups (nur Schulterblätter)",
          "10× Katzenbuckel / Kuhstand (Wirbelsäule)",
        ],
      },
      exercises: [
        {
          id: "pull-klimmzuege",
          badge: "1",
          badgeColor: "orange",
          name: "Gewichtete Klimmzüge",
          cue: "Untergriff / Neutralgriff, volles ROM",
          footerNote: "Zusatzgewicht wenn 8 Wdh. sauber möglich",
          loadType: "bodyweight_loaded",
          pauseLabel: "2–3 Min",
          pauseSeconds: 150,
          movements: [{ sets: 4, repType: "range", repMin: 5, repMax: 7 }],
          progression: { strategy: "bodyweight-add-weight-at-threshold", thresholdReps: 8, addKg: 2.5, role: "main" },
        },
        {
          id: "pull-pendlay-row",
          badge: "2",
          badgeColor: "orange",
          name: "Pendlay Row (Langhantel)",
          cue: "Stab berührt Boden nach jeder Wdh.",
          footerNote: "Explosiv hoch, kontrolliert absenken",
          loadType: "barbell",
          pauseLabel: "2 Min",
          pauseSeconds: 120,
          movements: [{ sets: 4, repType: "range", repMin: 6, repMax: 8 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "main" },
        },
        {
          id: "pull-ring-rows",
          badge: "3",
          badgeColor: "purple",
          name: "Ring Rows (Turnringe)",
          cue: "Winkel je nach Stärke, Körper gerade",
          footerNote: "Schulterblätter am Ende zusammenziehen",
          loadType: "bodyweight",
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [{ sets: 3, repType: "range", repMin: 10, repMax: 12 }],
          progression: { strategy: "reps-then-weight", role: "assist" },
        },
        {
          id: "pull-einarmiges-rudern",
          badge: "4",
          badgeColor: "purple",
          name: "Einarmiges Rudern (KH)",
          cue: "Abstützen auf Bank, langer Zug",
          footerNote: "Ellenbogen eng, Rücken neutral",
          loadType: "dumbbell",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "range", repMin: 10, repMax: 12 }],
          progression: { strategy: "range-weight", incrementKg: 2, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "pull-ez-curl",
          badge: "5",
          badgeColor: "green",
          name: "EZ-Stangen Curl (Untergriff)",
          cue: "Stehend, Ellenbogen fixiert",
          footerNote: "Volle Streckung am unteren Wendepunkt",
          loadType: "barbell",
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [{ sets: 4, repType: "range", repMin: 8, repMax: 10 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "pull-hammer-curl",
          badge: "6",
          badgeColor: "green",
          name: "Hammer Curl (KH alternierend)",
          cue: "Neutralgriff, kein Schwung",
          footerNote: "Brachialis + langer Bizepskopf",
          loadType: "dumbbell",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "range", repMin: 10, repMax: 12 }],
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
      ],
      progressionNotes: [
        "Klimmzüge: Zusatzgewicht sobald 8 Wdh. möglich.",
        "Curls: alle 2 Wochen +2,5 kg oder +1 Wdh. anstreben.",
        "RPE Hauptübungen: 8–9 • Assistenz: 7–8",
      ],
    },

    {
      id: "tag3-metabolic",
      dayNumber: 3,
      title: "Metabolic",
      subtitle: "Fettverbrennung • Kondition • Ganzkörper",
      accent: "orange",
      isCircuitDay: true,
      warmup: {
        minutes: "8",
        items: [
          "3 Min Airbike (mittleres Tempo aufbauen)",
          "10× World's Greatest Stretch (pro Seite)",
          "10× Goblet Squat mit KB 16 kg (Mobilität)",
          "10× Hip Hinge mit Stab (Technik für KB-Swings)",
        ],
      },
      intervalBlock: {
        id: "block-a",
        label: "Airbike Intervalle",
        cue: "20 Sek Sprint (90–95%) / 40 Sek locker × 10 Runden",
        footerNote: "Ab Woche 3: 25 Sek Sprint / 35 Sek locker × 12",
        totalLabel: "~10 Min",
        baseRounds: 10,
        workSeconds: 20,
        restSeconds: 40,
        week3Plus: { rounds: 12, workSeconds: 25, restSeconds: 35 },
      },
      circuitBlock: {
        id: "block-b",
        rounds: 3,
        roundRestSeconds: 90,
        exercises: [
          { id: "metabolic-kb-swing", badge: "B1", badgeColor: "orange", name: "KB Swing Two-Hand", cue: "Hüfte schießt vor, Rücken gerade, Arme passiv", loadLabel: "KB 24 kg", workSeconds: 45 },
          { id: "metabolic-goblet-squat", badge: "B2", badgeColor: "purple", name: "Goblet Squat", cue: "Knie über Zehen, Brust hoch", loadLabel: "KB 24 kg", workSeconds: 45 },
          { id: "metabolic-clean-press", badge: "B3", badgeColor: "orange", name: "KB Clean & Press (alt.)", cue: "Sauber cleanen, volle Hüftstreckung", loadLabel: "KB 16–24 kg", workSeconds: 45 },
          { id: "metabolic-box-jump", badge: "B4", badgeColor: "purple", name: "Box Jump / Step-Up", cue: "Weich landen, Hüfte oben durchstrecken", loadLabel: "Box", workSeconds: 45 },
          { id: "metabolic-renegade-row", badge: "B5", badgeColor: "green", name: "Renegade Row", cue: "Core fest, keine Rotation • 3 Runden gesamt", loadLabel: "KH 17,5–20 kg", workSeconds: 45 },
        ],
      },
      finisher: { label: "Ruder-Finisher", detail: "250 m × 5, danach Cool-Down." },
      exercises: [],
      progressionNotes: [
        "Block B Ablauf: B1→B2→B3→B4→B5 ohne Pause, dann 90 Sek Pause, danach Runde 2 von 3.",
        "Ruder-Finisher: 250 m ×5, danach Cool-Down.",
      ],
    },

    {
      id: "tag4-beine",
      dayNumber: 4,
      title: "Beine",
      subtitle: "Quadrizeps • Ischio • Gesäß • Posterior Chain",
      accent: "orange",
      warmup: {
        minutes: "8–10",
        items: [
          "5 Min Rudergerät (mittleres Tempo)",
          "10× Bodyweight Squat (tief, Fersen am Boden)",
          "10× Glute Bridge • 10× Leg Swings pro Seite",
          "2 Aufwärmsätze Kniebeuge (60 % Arbeitsgewicht)",
        ],
      },
      exercises: [
        {
          id: "beine-kniebeuge",
          badge: "1",
          badgeColor: "orange",
          name: "Kniebeuge (Langhantel, Low Bar)",
          cue: "Power Rack, Sicherung korrekt einstellen",
          footerNote: "Oberschenkel mind. parallel, Rücken neutral",
          loadType: "barbell",
          pauseLabel: "2–3 Min",
          pauseSeconds: 150,
          movements: [{ sets: 4, repType: "range", repMin: 6, repMax: 8 }],
          progression: { strategy: "range-weight", incrementKg: 3.75, incrementRangeKg: [2.5, 5], cadenceWeeks: 1.5, role: "main" },
        },
        {
          id: "beine-rdl",
          badge: "2",
          badgeColor: "orange",
          name: "Romanian Deadlift (Langhantel)",
          cue: "Ischio-Fokus, langsam und kontrolliert",
          footerNote: "3-Sek-Negativ, Hüfte zieht nach hinten",
          loadType: "barbell",
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 4, repType: "range", repMin: 8, repMax: 10 }],
          progression: { strategy: "tempo-focus", role: "main" },
        },
        {
          id: "beine-box-stepup",
          badge: "3",
          badgeColor: "purple",
          name: "Box Step-Up (KH oder KB)",
          cue: "Knie arbeitet, Hüfte streckt oben durch",
          footerNote: "Gewicht in der Hand der hebenden Seite",
          loadType: "dumbbell",
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [{ sets: 3, repType: "perSide", repFixed: 10 }],
          progression: { strategy: "range-weight", incrementKg: 2, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "beine-sumo-deadlift",
          badge: "4",
          badgeColor: "purple",
          name: "KB Sumo Deadlift",
          cue: "Weite Fußstellung, KB 24 kg zwischen Beinen",
          footerNote: "Innere Oberschenkel und Gesäß betonen",
          loadType: "kettlebell",
          pauseLabel: "75 Sek",
          pauseSeconds: 75,
          movements: [{ sets: 3, repType: "range", repMin: 12, repMax: 15 }],
          progression: { strategy: "range-weight", incrementKg: 4, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "beine-glute-bridge",
          badge: "5",
          badgeColor: "green",
          name: "Einbeinige Glute Bridge (Bank)",
          cue: "Schultern auf Bank, Hüfte hebt",
          footerNote: "Pause oben, Gesäß maximal anspannen",
          loadType: "bodyweight",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "perSide", repFixed: 12 }],
          progression: { strategy: "reps-then-weight", role: "assist" },
        },
        {
          id: "beine-kb-swing-single",
          badge: "6",
          badgeColor: "green",
          name: "KB Swing Single-Hand (alt.)",
          cue: "KB 24 kg, Wechsel in der Luft",
          footerNote: "Aktiviert Posterior Chain + Herz-Kreislauf",
          loadType: "kettlebell",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [{ sets: 3, repType: "fixed", repFixed: 20, repFixedLabel: "20 ges." }],
          progression: { strategy: "tempo-focus", role: "assist" },
        },
      ],
      progressionNotes: [
        "Kniebeuge: alle 1–2 Wochen +2,5–5 kg.",
        "RDL: Tempo wichtiger als Gewicht – 3 Sek negativ.",
        "RPE Hauptübungen: 8–9 • Assistenz: 7–8",
      ],
    },

    {
      id: "tag5-arme",
      dayNumber: 5,
      title: "Arme",
      subtitle: "Bizeps • Trizeps • Unterarme • Spezial",
      accent: "orange",
      warmup: {
        minutes: "6",
        items: [
          "3 Min Airbike (locker)",
          "2× 15 Wdh. Curl mit Stab ohne Gewicht",
          "2× 15 Wdh. Trizepsdrücken über Kopf ohne Gewicht",
          "Dead Hang 30 Sek (Ellenbogen + Schultern)",
        ],
      },
      exercises: [
        {
          id: "arme-ez-curl-superset",
          badge: "A1",
          badgeColor: "orange",
          name: "EZ-Stangen Curl (Untergriff)",
          cue: "Superset A – direkt gefolgt von A2, dann 90s Pause",
          footerNote: "Volle Streckung unten, 2 Sek oben halten",
          loadType: "barbell",
          pauseLabel: "→ A2",
          chainNext: "arme-overhead-extension",
          movements: [{ sets: 4, repType: "range", repMin: 8, repMax: 10 }],
          progression: { strategy: "range-weight", incrementKg: 2.5, cadenceWeeks: 2, role: "main" },
        },
        {
          id: "arme-overhead-extension",
          badge: "A2",
          badgeColor: "orange",
          name: "EZ-Stange Overhead Extension",
          cue: "Stehend oder sitzend, Ellenbogen nah am Kopf",
          footerNote: "Langen Trizepskopf betonen, kontrolliert",
          loadType: "barbell",
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 4, repType: "range", repMin: 10, repMax: 12 }],
          progression: { strategy: "range-weight", incrementKg: 1.25, cadenceWeeks: 2, role: "main" },
        },
        {
          id: "arme-hammer-curl-superset",
          badge: "B1",
          badgeColor: "purple",
          name: "Hammer Curl (KH alternierend)",
          cue: "Superset B – direkt gefolgt von B2, dann 90s Pause",
          footerNote: "Brachialis + langer Bizepskopf = Armvolumen",
          loadType: "dumbbell",
          pauseLabel: "→ B2",
          chainNext: "arme-ring-dips",
          movements: [{ sets: 3, repType: "range", repMin: 10, repMax: 12 }],
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "arme-ring-dips",
          badge: "B2",
          badgeColor: "purple",
          name: "Ring Dips",
          cue: "Ringe nah am Körper, Ellenbogen eng",
          footerNote: "Körper senkrecht = maximaler Trizeps-Fokus",
          loadType: "bodyweight_loaded",
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [{ sets: 3, repType: "range", repMin: 8, repMax: 12 }],
          progression: { strategy: "bodyweight-add-weight-at-threshold", thresholdReps: 12, addKg: 2.5, role: "assist" },
        },
        {
          id: "arme-concentration-cg",
          badge: "C",
          badgeColor: "green",
          name: "Concentration Curl + Close-Grip",
          cue: "Superset C: 12 Wdh./Seite + 10–12 Wdh. CG-Bench",
          footerNote: "3 Sek negativ Curl, Ellenbogen eng bei Bench",
          loadType: "dumbbell",
          pauseLabel: "90 Sek",
          pauseSeconds: 90,
          movements: [
            { name: "Concentration Curl", sets: 3, repType: "perSide", repFixed: 12 },
            { name: "Close-Grip Bench", sets: 3, repType: "range", repMin: 10, repMax: 12, loadType: "barbell" },
          ],
          progression: { strategy: "range-weight", incrementKg: 1, cadenceWeeks: 2, role: "assist" },
        },
        {
          id: "arme-finisher",
          badge: "F",
          badgeColor: "green",
          name: "Finisher: 21s + Reverse Curl",
          cue: "21s EZ (7+7+7) • Reverse Curl 12–15 Wdh.",
          footerNote: "Unterarme trainieren = sichtbar dickere Arme",
          loadType: "barbell",
          pauseLabel: "60 Sek",
          pauseSeconds: 60,
          movements: [
            { name: "21s (EZ-Stange)", sets: 2, repType: "special21" },
            { name: "Reverse Curl", sets: 3, repType: "range", repMin: 12, repMax: 15 },
          ],
          progression: { strategy: "tempo-focus", role: "assist" },
        },
      ],
      progressionNotes: [
        "Curls: alle 2 Wochen +2,5 kg oder +1 Wdh.",
        "Ring Dips: Zusatzgewicht nach 12 Wdh. sauber.",
        "Pump ist das Signal – Armtag = max. Volumen",
      ],
    },
  ],
};

export function getDay(dayId) {
  return PLAN.days.find((d) => d.id === dayId);
}

export function getExercise(dayId, exerciseId) {
  const day = getDay(dayId);
  return day?.exercises.find((e) => e.id === exerciseId);
}

export function allStrengthExercises() {
  return PLAN.days.flatMap((d) => d.exercises.map((e) => ({ ...e, dayId: d.id, dayTitle: d.title })));
}
